### ISSUE TITLE
How did the authors combine values and the five theories?

### ISSUE THREAD

**Issue by kkckk1110** [kellycyy/daily_dilemmas#1]
Hello, I found the work really impressive and it provides me with many valuable insights. But I have a question about combining values and the five theories. In the value.csv, each human value generated by LLM is correlated with an aspect of a particular theory. Could you please explain how this correlation was achieved? Did the authors manually identified the aspect the value belonging to, or did the authors utilize LLMs to solve the problem? Thanks a lot for your attention.

**Comment by kellycyy** [comment]
Thanks for reaching out! We did it manually to check if the definitions of the values fit into the definition of dimensions in each theory.
